services:
  backend:
    build: .
    container_name: spring-backend
    tty: true
    ports:
      - "8080:8080"
    environment:
      SUPABASE_URL: ${API_URL}
      SUPABASE_KEY: ${API_KEY}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
